# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_demo do
    beta_gym_s3
  end


  lane :beta_gym_s3 do
	  ensure_git_status_clean(
	  	show_uncommitted_changes: true
	  )

	  bump_build_number
	  build_beta
	  upload_s3
	  clean_build_artifacts
	  commit_version_bump(
	  	message: "Build #{current_build_number}",
	  	xcodeproj: "WizeViewML.xcodeproj"
	  	)
	  push_to_git_remote
  end

  private_lane :current_version_number do
  	version_number = get_version_number(
  		xcodeproj:"WizeViewML.xcodeproj",
  		target:"WizeViewML")
  	UI.message "Current Version: #{version_number}"
  	version_number
  end

  private_lane :current_build_number do
  	build_number = get_build_number(
  		xcodeproj:"WizeViewML.xcodeproj")
  	UI.message "Current Build: #{build_number}"
  	build_number
  end

  private_lane :bump_build_number do
  	is_master_branch = git_branch == "master"

  	if is_master_branch
  		current_build_number = get_build_number
  		final_build_number = increment_build_number
  	else
  		current_build_number = get_build_number.to_f
  		new_build_number = current_build_number + 0.01
  		UI.message "New build number #{new_build_number.round(2).to_s}"
  		final_build_number = increment_build_number(build_number: new_build_number.round(2).to_s)
  	end
  end

  lane :build_beta do
  	gym(
  		scheme: "WizeViewML",
  		export_method: "development")
  end

  lane :upload_s3 do |options|
  	aws_s3(
          access_key: "AKIAJY52DSG7437IAM2Q",
          secret_access_key: "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",
          bucket: "download.airdropapps.com",
          region: "us-east-1",
          ipa: "WizeViewML.ipa",
          app_directory: "wizeview",
          upload_metadata: true
      )
  end

end
